### ISSUE TITLE
Security problem with your Reddit account

### ISSUE THREAD

**Issue by rememberYou** [s3pp3ku/dotfiles#1]
First of all, thank you for sharing your dotfiles.

I would like to point out that you have clearly displayed the JSON link to your reddit account, which contains sensitive information and therefore a security problem:
`url='https://www.reddit.com/message/inbox/.json?feed=467e5629794e7d30d03380afc89eb8d7b0b9c017&user=Zombie_Scourge'`

Source: [reddit.sh](https://github.com/s3pp3ku/dotfiles/blob/f0bb7cc5e3528e084c99d2e0f97d191a6414ccfd/polybar/scripts/reddit.sh)

The solution to this would be for you to place this link in a GPG file so that you can easily share it without risk.

Here is a solution I implemented:
```
# Replace this path by yours.
reddit_gpg="/home/$USER/Sync/shared/.reddit-json.gpg"
url="https://www.reddit.com/message/unread/.json?feed=$(gpg -qd "$reddit_gpg")"
```

The complete script is available in my [dotfiles](https://github.com/rememberYou/dotfiles/blob/master/bin/bin/polybar-reddit.sh).

Please remember to change your password so that a new JSON link is regenerated.

**Comment by s3pp3ku** [comment]
Hey, thanks for bringing this to my attention.

**Comment by rememberYou** [comment]
You're welcome.
